import { invertKeymap } from "../data/keymap";
import type { KeybindingConfig } from "../types/keybinding";
import { VIM_MODES } from "../types/keybinding";

/**
 * Lua 文字列リテラル用エスケープ。
 * `\` と `"` を対象とし、`vim.keymap.set()` の引数として使用される。
 */
function escapeLua(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

export function keybindingToLua(config: KeybindingConfig): string {
  const lines: string[] = ["-- Generated by nv-atlas", ""];

  for (const mode of VIM_MODES) {
    const bindings = config.bindings[mode];
    if (bindings.length === 0) continue;

    lines.push(`-- ${mode} mode`);
    for (const binding of bindings) {
      const rhs = binding.rhs ?? binding.commandId;
      if (!rhs) continue;
      const lhsEscaped = escapeLua(binding.lhs);
      const rhsEscaped = escapeLua(rhs);
      const noremapVal = binding.noremap ? "true" : "false";
      lines.push(
        `vim.keymap.set("${mode}", "${lhsEscaped}", "${rhsEscaped}", { noremap = ${noremapVal} })`,
      );
    }
    lines.push("");
  }

  return lines.join("\n");
}

export function keybindingToJSON(config: KeybindingConfig): string {
  return JSON.stringify(config, null, 2);
}

/**
 * Vim `langmap` オプション用エスケープ。
 * `\`, `,`, `;`, `"` の 4 文字を対象とし、`vim.opt.langmap` の値として使用される。
 */
function escapeLangmapChar(char: string): string {
  return char.replace(/[\\,;"]/g, (c) => `\\${c}`);
}

export function keybindingToLangmap(config: KeybindingConfig): string {
  if (config.customKeymap === undefined) {
    return "";
  }

  const inverted = invertKeymap(config.customKeymap);

  const pairs: string[] = [];
  for (const [from, to] of Object.entries(inverted)) {
    if (from === to) continue;
    pairs.push(`${escapeLangmapChar(from)}${escapeLangmapChar(to)}`);
  }

  if (pairs.length === 0) {
    return "";
  }

  return `vim.opt.langmap = "${pairs.join(",")}"`;
}
